# Generated by Django 4.1.7 on 2023-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
