# Generated by Django 4.1.7 on 2023-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='style',
        ),
    ]
