# Generated by Django 4.1.7 on 2023-04-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_country_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zonecode', models.IntegerField(default=1)),
                ('zonename', models.CharField(blank=True, max_length=20)),
                ('countrycode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['zonename'],
            },
        ),
    ]
