# Generated by Django 4.1.7 on 2023-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statecode', models.IntegerField(default=1)),
                ('zonecode', models.IntegerField(blank=True)),
                ('countrycode', models.IntegerField(blank=True)),
                ('statename', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['statename'],
            },
        ),
    ]
