# Generated by Django 4.1.7 on 2023-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countrycode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
