# Generated by Django 4.1.7 on 2023-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_country_countrycode_alter_country_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areamaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statecode', models.IntegerField(default=1)),
                ('zonecode', models.IntegerField()),
                ('countrycode', models.IntegerField()),
                ('areacode', models.IntegerField()),
                ('areaname', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['areaname'],
            },
        ),
    ]
