# Generated by Django 4.1.7 on 2023-04-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_areamaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('districtcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('statecode', models.IntegerField()),
                ('districtname', models.CharField(blank=True, max_length=50)),
                ('countrycode', models.IntegerField()),
                ('areacode', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['districtname'],
            },
        ),
        migrations.CreateModel(
            name='Menumaster',
            fields=[
                ('menuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('menucaption', models.CharField(blank=True, max_length=50)),
                ('pos', models.IntegerField()),
            ],
            options={
                'ordering': ['menucaption'],
            },
        ),
        migrations.CreateModel(
            name='Modelmaster',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('modelcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('productcode', models.IntegerField()),
                ('modelname', models.CharField(blank=True, max_length=50)),
                ('cylinder', models.CharField(blank=True, max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['modelname'],
            },
        ),
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=50)),
                ('fileid', models.IntegerField()),
                ('moduleid', models.IntegerField()),
                ('userstatus', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
        migrations.CreateModel(
            name='Userinformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('employeecode', models.CharField(blank=True, max_length=50)),
                ('isactive', models.BooleanField(default=True)),
                ('user_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('citycode', models.BigAutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, max_length=50)),
                ('stdcode', models.BigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('statecode', models.IntegerField()),
                ('countrycode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('districtcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state')),
            ],
            options={
                'ordering': ['cityname'],
            },
        ),
    ]
