# Generated by Django 4.1.7 on 2023-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_district_menumaster_modelmaster_userauthorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('fileid', models.BigAutoField(primary_key=True, serialize=False)),
                ('menuid', models.IntegerField()),
                ('filemenuname', models.CharField(blank=True, max_length=50)),
                ('filepath', models.CharField(default='#', max_length=200)),
                ('menu_icon', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('menuseq', models.IntegerField()),
                ('element', models.CharField(blank=True, max_length=300)),
                ('sub_menu', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['filemenuname'],
            },
        ),
        migrations.CreateModel(
            name='FileInternal',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('file_id', models.BigIntegerField(blank=True)),
                ('file_sub_route_id', models.BigIntegerField(blank=True)),
                ('element', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('stockistcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('distributorcode', models.CharField(blank=True, max_length=100)),
                ('citycode', models.IntegerField()),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('emailid', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('phoneno', models.CharField(blank=True, max_length=30)),
                ('faxno', models.CharField(blank=True, max_length=30)),
                ('statecode', models.IntegerField()),
                ('districtcode', models.IntegerField()),
                ('tehsilcode', models.IntegerField()),
                ('stockisttype', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('altphoneno', models.CharField(blank=True, max_length=30)),
                ('countrycode', models.IntegerField()),
                ('area', models.CharField(blank=True, max_length=50)),
                ('concernperson', models.CharField(blank=True, max_length=300)),
                ('foryear', models.CharField(blank=True, max_length=30)),
                ('appointdate', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('transportcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('transportname', models.CharField(blank=True, max_length=30)),
                ('mobileno', models.CharField(blank=True, max_length=30)),
                ('emailid', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('citycode', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('alternatephoneno', models.CharField(blank=True, max_length=15)),
                ('statecode', models.IntegerField()),
                ('districtcode', models.IntegerField(blank=True)),
                ('faxno', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['transportname'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('transportcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('productcode', models.IntegerField()),
                ('vehicleno', models.CharField(max_length=50)),
                ('vehiclename', models.CharField(blank=True, max_length=50)),
                ('drivername', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['vehiclename'],
            },
        ),
    ]
