# Generated by Django 4.1.7 on 2023-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_remove_file_id_alter_file_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='menuid',
            field=models.IntegerField(blank=True),
        ),
    ]
