# Generated by Django 4.1.7 on 2023-04-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_userinformation_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinformation',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user_permissions',
        ),
    ]
