# Generated by Django 4.1.7 on 2023-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_userinformation_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('employeecode', models.BigAutoField(primary_key=True, serialize=False)),
                ('designationcode', models.IntegerField(default=1)),
                ('employeename', models.CharField(max_length=250)),
                ('departmentid', models.IntegerField()),
                ('phoneno', models.CharField(blank=True, max_length=10)),
                ('mobileno', models.CharField(blank=True, max_length=10)),
                ('emailid', models.CharField(blank=True, max_length=250)),
                ('dateofjoining', models.DateTimeField()),
                ('reportingdesgination', models.IntegerField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['employeename'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeArea',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('employeearea', models.BigAutoField(primary_key=True, serialize=False)),
                ('employeecode', models.CharField(max_length=20)),
                ('reportingemployeecode', models.CharField(max_length=20)),
                ('designationcode', models.IntegerField(blank=True)),
                ('reportingdesignationcode', models.IntegerField(blank=True)),
                ('countrycode', models.IntegerField(blank=True)),
                ('zonecode', models.IntegerField(blank=True)),
                ('statecode', models.IntegerField(blank=True)),
                ('areacode', models.IntegerField(blank=True)),
                ('dealercode', models.IntegerField(blank=True)),
                ('distributorcode', models.IntegerField(blank=True)),
                ('districtcode', models.IntegerField(blank=True)),
                ('assigndate', models.IntegerField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['reportingemployeecode'],
            },
        ),
        migrations.CreateModel(
            name='Tehsi',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('tehsilcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('citycode', models.IntegerField()),
                ('tehsilname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['tehsilname'],
            },
        ),
    ]
