# Generated by Django 4.1.7 on 2023-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_employee_employeearea_tehsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('productcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
