# Generated by Django 4.1.7 on 2023-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_productdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('countrycode', models.IntegerField()),
                ('statecode', models.IntegerField()),
                ('areacode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('areaname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['areaname'],
            },
        ),
    ]
