# Generated by Django 4.1.7 on 2023-06-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='countrycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
    ]
