# Generated by Django 4.1.7 on 2023-06-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_area_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='countrycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
    ]
