# Generated by Django 4.1.7 on 2023-06-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_alter_state_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamaster',
            name='statecode',
            field=models.IntegerField(),
        ),
    ]
