# Generated by Django 4.1.7 on 2023-06-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_alter_areamaster_statecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='statecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state'),
        ),
    ]
